from Utilities import *

DetailedState_DisabledState = 1
DetailedState_EnabledState = 2
DetailedState_FaultState = 3
DetailedState_OfflineState = 4
DetailedState_StandbyState = 5
DetailedState_ParkedState = 6
DetailedState_RaisingState = 7
DetailedState_ActiveState = 8
DetailedState_LoweringState = 9
DetailedState_EngineeringState = 10
DetailedState_ParkedEngineeringState = 11
DetailedState_RaisingEngineeringState = 12
DetailedState_ActiveEngineeringState = 13
DetailedState_LoweringEngineeringState = 14
DetailedState_LoweringFaultState = 15
DetailedState_ProfileHardpointCorrectionState = 16

class VerifyStateChanges:
    def Run(self, m1m3, sim):
        self.CheckParameterValidation(m1m3, sim)
        self.CheckStateValidation(m1m3, sim)
        
    def CheckParameterValidation(self, m1m3, sim):
        Header("VerifyStateChanges: CheckParameterValidation")
        m1m3.Start("Default", False)
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.Enable(False)
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Enable Rejected", result, 0)
        m1m3.RaiseM1M3(False, False)
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Raise M1M3 Rejected", result, 0)
        m1m3.AbortRaiseM1M3(False)
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Abort RaiseM1M3 Rejected", result, 0)
        m1m3.LowerM1M3(False)
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Lower M1M3 Rejected", result, 0)
        m1m3.EnterEngineering(False)
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Enter Engineering Rejected", result, 0)
        m1m3.ExitEngineering(False)
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Exit Engineering Rejected", result, 0)
        m1m3.Disable(False)
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Disable Rejected", result, 0)
        m1m3.Standby(False)
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Standby Rejected", result, 0)
        m1m3.Shutdown(False)
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Shutdown Rejected", result, 0)
        
    def CheckStateValidation(self, m1m3, sim):
        Header("VerifyStateChanges: CheckStateValidation")
        self.CheckStandbyState(m1m3, sim)
        self.CheckDisabledState(m1m3, sim)
        self.CheckParkState(m1m3, sim)
        self.CheckRaisingState(m1m3, sim)
        self.CheckActiveState(m1m3, sim)
        self.CheckLoweringState(m1m3, sim)
        self.CheckParkEngineeringState(m1m3, sim)
        self.CheckRaisingEngineeringState(m1m3, sim)
        self.CheckActiveEngineeringState(m1m3, sim)
        self.CheckLoweringEngineeringState(m1m3, sim)
        
    def CheckStandbyState(self, m1m3, sim):
        m1m3.Start("Default")
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Standby()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_StandbyState)
        m1m3.Enable()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Enable Rejected", result, 0)
        m1m3.RaiseM1M3(False)
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Raise M1M3 Rejected", result, 0)
        m1m3.AbortRaiseM1M3()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Abort RaiseM1M3 Rejected", result, 0)
        m1m3.LowerM1M3()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Lower M1M3 Rejected", result, 0)
        m1m3.EnterEngineering()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Enter Engineering Rejected", result, 0)
        m1m3.ExitEngineering()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Exit Engineering Rejected", result, 0)
        m1m3.Disable()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Disable Rejected", result, 0)
        m1m3.Standby()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Standby Rejected", result, 0)
        # Ignore because this will shutdown the software
        #m1m3.Shutdown()
        #result, data = m1m3.GetEventCommandRejectionWarning()
        #Equal("Shutdown Rejected", result, 0)
        
    def CheckDisabledState(self, m1m3, sim):
        m1m3.Start("Default")
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Start("Default")
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.Enable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedState)
        m1m3.Disable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.RaiseM1M3(False)
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Raise M1M3 Rejected", result, 0)
        m1m3.AbortRaiseM1M3()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Abort RaiseM1M3 Rejected", result, 0)
        m1m3.LowerM1M3()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Lower M1M3 Rejected", result, 0)
        m1m3.EnterEngineering()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Enter Engineering Rejected", result, 0)
        m1m3.ExitEngineering()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Exit Engineering Rejected", result, 0)
        m1m3.Disable()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Disable Rejected", result, 0)
        m1m3.Standby()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_StandbyState)
        m1m3.Start("Default")
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Shutdown()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Shutdown Rejected", result, 0)
        m1m3.Standby()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_StandbyState)
        
    def CheckParkState(self, m1m3, sim):
        m1m3.Start("Default")
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Enable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedState)
        m1m3.Start("Default")
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.Enable()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.RaiseM1M3(False)
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_RaisingState)
        m1m3.AbortRaiseM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_LoweringState)
        WaitUntil("DetailedState", 300, lambda: m1m3.EventDetailedState().DetailedState == DetailedState_ParkedState)        
        m1m3.AbortRaiseM1M3()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Abort RaiseM1M3 Rejected", result, 0)
        m1m3.LowerM1M3()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Lower M1M3 Rejected", result, 0)
        m1m3.EnterEngineering()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedEngineeringState)
        m1m3.ExitEngineering()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedState)
        m1m3.ExitEngineering()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Exit Engineering Rejected", result, 0)
        m1m3.Disable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Enable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedState)
        m1m3.Standby()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.Shutdown()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Shutdown Rejected", result, 0)
        m1m3.Disable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Standby()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_StandbyState)
        
    def CheckRaisingState(self, m1m3, sim):
        m1m3.Start("Default")
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Enable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedState)
        m1m3.RaiseM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_RaisingState)
        m1m3.Start("Default")
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.Enable()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.RaiseM1M3(False)
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Raise M1M3 Rejected", result, 0)
        m1m3.AbortRaiseM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_LoweringState)
        WaitUntil("DetailedState", 300, lambda: m1m3.EventDetailedState().DetailedState == DetailedState_ParkedState)        
        m1m3.RaiseM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_RaisingState)
        m1m3.LowerM1M3()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Lower M1M3 Rejected", result, 0)
        m1m3.EnterEngineering()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Enter Engineering Rejected", result, 0)
        m1m3.ExitEngineering()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Exit Engineering Rejected", result, 0)
        m1m3.Disable()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Disable Rejected", result, 0)
        m1m3.Standby()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.Shutdown()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Shutdown Rejected", result, 0)
        m1m3.AbortRaiseM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_LoweringState)
        WaitUntil("DetailedState", 300, lambda: m1m3.EventDetailedState().DetailedState == DetailedState_ParkedState)
        m1m3.Disable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Standby()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_StandbyState)
        
    def CheckActiveState(self, m1m3, sim):
        m1m3.Start("Default")
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Enable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedState)
        m1m3.RaiseM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_RaisingState)
        WaitUntil("DetailedState", 300, lambda: m1m3.EventDetailedState().DetailedState == DetailedState_ActiveState)        
        m1m3.Start("Default")
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.Enable()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.RaiseM1M3(False)
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Raise M1M3 Rejected", result, 0)
        m1m3.AbortRaiseM1M3()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Abort RaiseM1M3 Rejected", result, 0)
        m1m3.LowerM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_LoweringState)
        WaitUntil("DetailedState", 300, lambda: m1m3.EventDetailedState().DetailedState == DetailedState_ParkedState)     
        m1m3.RaiseM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_RaisingState)
        WaitUntil("DetailedState", 300, lambda: m1m3.EventDetailedState().DetailedState == DetailedState_ActiveState)
        m1m3.EnterEngineering()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ActiveEngineeringState)
        m1m3.ExitEngineering()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ActiveState)
        m1m3.ExitEngineering()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Exit Engineering Rejected", result, 0)
        m1m3.Disable()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Disable Rejected", result, 0)
        m1m3.Standby()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.Shutdown()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Shutdown Rejected", result, 0)
        m1m3.LowerM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_LoweringState)
        WaitUntil("DetailedState", 300, lambda: m1m3.EventDetailedState().DetailedState == DetailedState_ParkedState)  
        m1m3.Disable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Standby()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_StandbyState)
        
    def CheckLoweringState(self, m1m3, sim):
        m1m3.Start("Default")
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Enable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedState)
        m1m3.RaiseM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_RaisingState)
        WaitUntil("DetailedState", 300, lambda: m1m3.EventDetailedState().DetailedState == DetailedState_ActiveState)        
        m1m3.LowerM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_LoweringState)
        m1m3.Start("Default")
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.Enable()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.RaiseM1M3(False)
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Raise M1M3 Rejected", result, 0)
        m1m3.AbortRaiseM1M3()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Abort RaiseM1M3 Rejected", result, 0)
        m1m3.LowerM1M3()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Lower M1M3 Rejected", result, 0)
        m1m3.EnterEngineering()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Enter Engineering Rejected", result, 0)
        m1m3.ExitEngineering()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Exit Engineering Rejected", result, 0)
        m1m3.Disable()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Disable Rejected", result, 0)
        m1m3.Standby()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.Shutdown()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Shutdown Rejected", result, 0)
        WaitUntil("DetailedState", 300, lambda: m1m3.EventDetailedState().DetailedState == DetailedState_ParkedState)  
        m1m3.Disable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Standby()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_StandbyState)
        
    def CheckParkEngineeringState(self, m1m3, sim):
        m1m3.Start("Default")
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Enable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedState)
        m1m3.EnterEngineering()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedEngineeringState)
        m1m3.Start("Default")
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.Enable()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.RaiseM1M3(False)
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_RaisingEngineeringState)
        m1m3.AbortRaiseM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_LoweringEngineeringState)
        WaitUntil("DetailedState", 300, lambda: m1m3.EventDetailedState().DetailedState == DetailedState_ParkedEngineeringState)        
        m1m3.AbortRaiseM1M3()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Abort RaiseM1M3 Rejected", result, 0)
        m1m3.LowerM1M3()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Lower M1M3 Rejected", result, 0)
        m1m3.EnterEngineering()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Enter Engineering Rejected", result, 0)
        m1m3.ExitEngineering()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedState)
        m1m3.EnterEngineering()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedEngineeringState)
        m1m3.Disable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Enable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedState)
        m1m3.EnterEngineering()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedEngineeringState)
        m1m3.Standby()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.Shutdown()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Shutdown Rejected", result, 0)
        m1m3.Disable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Standby()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_StandbyState)
        
    def CheckRaisingEngineeringState(self, m1m3, sim):
        m1m3.Start("Default")
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Enable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedState)
        m1m3.EnterEngineering()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedEngineeringState)
        m1m3.RaiseM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_RaisingEngineeringState)
        m1m3.Start("Default")
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.Enable()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.RaiseM1M3(False)
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Raise M1M3 Rejected", result, 0)
        m1m3.AbortRaiseM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_LoweringEngineeringState)
        WaitUntil("DetailedState", 300, lambda: m1m3.EventDetailedState().DetailedState == DetailedState_ParkedEngineeringState)        
        m1m3.RaiseM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_RaisingEngineeringState)
        m1m3.LowerM1M3()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Lower M1M3 Rejected", result, 0)
        m1m3.EnterEngineering()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Enter Engineering Rejected", result, 0)
        m1m3.ExitEngineering()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Exit Engineering Rejected", result, 0)
        m1m3.Disable()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Disable Rejected", result, 0)
        m1m3.Standby()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.Shutdown()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Shutdown Rejected", result, 0)
        m1m3.AbortRaiseM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_LoweringEngineeringState)
        WaitUntil("DetailedState", 300, lambda: m1m3.EventDetailedState().DetailedState == DetailedState_ParkedEngineeringState)
        m1m3.Disable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Standby()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_StandbyState)
        
    def CheckActiveEngineeringState(self, m1m3, sim):
        m1m3.Start("Default")
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Enable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedState)
        m1m3.EnterEngineering()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedEngineeringState)
        m1m3.RaiseM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_RaisingEngineeringState)
        WaitUntil("DetailedState", 300, lambda: m1m3.EventDetailedState().DetailedState == DetailedState_ActiveEngineeringState)        
        m1m3.Start("Default")
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.Enable()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.RaiseM1M3(False)
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Raise M1M3 Rejected", result, 0)
        m1m3.AbortRaiseM1M3()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Abort RaiseM1M3 Rejected", result, 0)
        m1m3.LowerM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_LoweringEngineeringState)
        WaitUntil("DetailedState", 300, lambda: m1m3.EventDetailedState().DetailedState == DetailedState_ParkedEngineeringState)     
        m1m3.RaiseM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_RaisingEngineeringState)
        WaitUntil("DetailedState", 300, lambda: m1m3.EventDetailedState().DetailedState == DetailedState_ActiveEngineeringState)
        m1m3.EnterEngineering()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Enter Engineering Rejected", result, 0)
        m1m3.ExitEngineering()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ActiveState)
        m1m3.EnterEngineering()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ActiveEngineeringState)
        m1m3.Disable()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Disable Rejected", result, 0)
        m1m3.Standby()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.Shutdown()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Shutdown Rejected", result, 0)
        m1m3.LowerM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_LoweringEngineeringState)
        WaitUntil("DetailedState", 300, lambda: m1m3.EventDetailedState().DetailedState == DetailedState_ParkedEngineeringState)  
        m1m3.Disable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Standby()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_StandbyState)
        
    def CheckLoweringEngineeringState(self, m1m3, sim):
        m1m3.Start("Default")
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Enable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedState)
        m1m3.EnterEngineering()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_ParkedEngineeringState)
        m1m3.RaiseM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_RaisingEngineeringState)
        WaitUntil("DetailedState", 300, lambda: m1m3.EventDetailedState().DetailedState == DetailedState_ActiveEngineeringState)        
        m1m3.LowerM1M3()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_LoweringEngineeringState)
        m1m3.Start("Default")
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.Enable()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.RaiseM1M3(False)
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Raise M1M3 Rejected", result, 0)
        m1m3.AbortRaiseM1M3()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Abort RaiseM1M3 Rejected", result, 0)
        m1m3.LowerM1M3()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Lower M1M3 Rejected", result, 0)
        m1m3.EnterEngineering()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Enter Engineering Rejected", result, 0)
        m1m3.ExitEngineering()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Exit Engineering Rejected", result, 0)
        m1m3.Disable()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Disable Rejected", result, 0)
        m1m3.Standby()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Start Rejected", result, 0)
        m1m3.Shutdown()
        result, data = m1m3.GetEventCommandRejectionWarning()
        Equal("Shutdown Rejected", result, 0)
        WaitUntil("DetailedState", 300, lambda: m1m3.EventDetailedState().DetailedState == DetailedState_ParkedEngineeringState)  
        m1m3.Disable()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_DisabledState)
        m1m3.Standby()
        result, data = m1m3.GetEventDetailedState()
        Equal("DetailedState", data.DetailedState, DetailedState_StandbyState)
    
        